# Generated by Django 4.1.2 on 2022-11-09 17:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Acre", "Ac"),
                            ("Alagoas", "Al"),
                            ("Amazonas", "Am"),
                            ("Amapá", "Ap"),
                            ("Bahia", "Ba"),
                            ("Ceará", "Ce"),
                            ("Distrito Federal", "Df"),
                            ("Espírito Santo", "Es"),
                            ("Goiás", "Go"),
                            ("Maranhão", "Ma"),
                            ("Minas Gerais", "Mg"),
                            ("Mato Grosso do Sul", "Ms"),
                            ("Mato Grosso", "Mt"),
                            ("Pará", "Pa"),
                            ("Paraíba", "Pb"),
                            ("Pernambuco", "Pe"),
                            ("Piauí", "Pi"),
                            ("Paraná", "Pr"),
                            ("Rio de Janeiro", "Rj"),
                            ("Rio Grande do Norte", "Rn"),
                            ("Rondônia", "Ro"),
                            ("Roraima", "Rr"),
                            ("Rio Grande do Sul", "Rs"),
                            ("Santa Catarina", "Sc"),
                            ("Sergipe", "Se"),
                            ("São Paulo", "Sp"),
                            ("Tocantins", "To"),
                            ("Not Defined", "Default"),
                        ],
                        default="Not Defined",
                        max_length=100,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("place", models.CharField(max_length=100)),
                ("number", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=8)),
                ("additional_data", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
