# Generated by Django 4.1.2 on 2022-11-09 17:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Borrowed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("initial_date", models.DateField(auto_now_add=True)),
                ("finish_date", models.DateField(null=True)),
                (
                    "shipping_method",
                    models.CharField(
                        choices=[("Correio", "Correio"), ("Retirada", "Retirada")],
                        max_length=100,
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrowed",
                        to="books.book",
                    ),
                ),
            ],
        ),
    ]
